name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-binaries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build binaries
        run: |
          make build-all-binaries
          ls -la 
          ls -la .build/
          ./package-github-binaries.sh
          ls -la dist/

      - name: Add binaries to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          allowUpdates: true
          omitBodyDuringUpdate: true


  build-and-push-docker-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.ARTIFACT_BUILDER_JSON_KEY }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            us-docker.pkg.dev/castai-hub/library/redis-exporter

      - name: Build and push scratch image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: scratch-release
          platforms: linux/amd64,linux/arm,linux/arm64
          push: true
          tags: us-docker.pkg.dev/castai-hub/library/redis-exporter:${{ github.ref_name }}-castai
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            TAG=${{ github.ref_name }}
            SHA1=${{ github.sha }}

      - name: Build and push alpine image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: alpine
          platforms: linux/amd64,linux/arm,linux/arm64
          push: true
          tags: us-docker.pkg.dev/castai-hub/library/redis-exporter:${{ github.ref_name }}-alpine-castai
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            TAG=${{ github.ref_name }}
            SHA1=${{ github.sha }}
